version: "3.8"

services:
  postgres:
    image: postgres:14
    restart: always
    ports:
      - '5432:5432'
    environment:
      - DATABASE_HOST=127.0.0.1
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=123asd456
      - POSTGRES_DB=activos
    volumes: 
      - ./postgres-data:/var/lib/postgresql/data